FROM python:3.12-slim
WORKDIR /app
ENV UV_PROJECT_ENVIRONMENT="/usr/local/"
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*
COPY pyproject.toml uv.lock ./
RUN pip install -U pip uv && uv sync --locked --group aiohttp
COPY performance/ ./performance
EXPOSE 8000
CMD ["python", "performance/server_aiohttp.py"]

